packages:
  - 'packages/*'
  - 'examples/*'
allowBuilds:
  '@swc/core': true

catalogs:
  testing:
    vitest: ^4.1.2
  tooling:
    '@swc/core': ^1.15.21
    '@typescript/native-preview': 7.0.0-dev.20260329.1
    tsdown: ^0.21.7
    unplugin-swc: ^1.5.9
  validation:
    valibot: ^1.3.1
    zod: ^4.1.12
  hono:
    hono: '^4.12.9'
